/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package adminCRUD;
import best_cars.ClientInterface;
import best_cars.ListePanne;
import best_cars.LoginClient;
import java.sql.*;
import ig.Connecteur;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adem
 */
public class listban extends javax.swing.JInternalFrame {
    private javax.swing.JDesktopPane jDesktopPane3;
    /**
     * Creates new form listban
     */
    public listban() {
        initComponents();
    }
    public listban(javax.swing.JDesktopPane jDesktopPanel) {
        
        this.jDesktopPane3=jDesktopPanel;
        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        recherche = new javax.swing.JButton();
        unban = new javax.swing.JButton();
        prenom_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        refresh1 = new javax.swing.JButton();
        cin_field = new javax.swing.JLabel();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cin", "nom", "prenom", "tel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        recherche.setText("search");
        recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheActionPerformed(evt);
            }
        });

        unban.setText("unban");
        unban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unbanActionPerformed(evt);
            }
        });

        prenom_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenom_fieldActionPerformed(evt);
            }
        });

        jLabel1.setText("cin:");

        jLabel2.setText("prenom:");

        refresh1.setText("Refresh");
        refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1ActionPerformed(evt);
            }
        });

        cin_field.setBackground(new java.awt.Color(197, 33, 33));
        cin_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prenom_field, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(cin_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(recherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(208, 228, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refresh1)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unban, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cin_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prenom_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(refresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Connection con ; 
    public void load(){
        Connecteur connect=new Connecteur();
       
        con = connect.connecttodb();
        String query = "SELECT * FROM banned";
        DefaultTableModel tablemodel =(DefaultTableModel) table.getModel();
        tablemodel.setRowCount(0);
        try {
            Statement stmt = con.createStatement();
            ResultSet res = stmt.executeQuery(query);
            
            while(res.next()){
                String cin = res.getString("CIN");
                String nom = res.getString("nom");
                String prenom = res.getString("prenom");
                String tel = res.getString("tel");
                tablemodel.addRow(new Object[]{cin,nom,prenom,tel});
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(listban.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
            DefaultTableModel model = (DefaultTableModel) table.getModel();
        int row = table.getSelectedRow();
        String cin =(String) model.getValueAt(row, 0);
        cin_field.setText(cin);
    }//GEN-LAST:event_tableMouseClicked
       
    private void rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheActionPerformed
        Connecteur connect=new Connecteur();
       
        con = connect.connecttodb();
        String prenom = prenom_field.getText();
        String query = "SELECT * FROM banned WHERE prenom = '"+prenom+"'";
        DefaultTableModel tablemodel =(DefaultTableModel) table.getModel();
        tablemodel.setRowCount(0);
        try {
            Statement stmt = con.createStatement();
            ResultSet res = stmt.executeQuery(query);

            while(res.next()){
                String cin = res.getString("CIN");
                String nom = res.getString("nom");
                prenom = res.getString("prenom");
                String tel = res.getString("tel");
                tablemodel.addRow(new Object[]{cin,nom,prenom,tel});

            }

        } catch (SQLException ex) {
            Logger.getLogger(listban.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rechercheActionPerformed

    private void unbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unbanActionPerformed
        Connecteur connect=new Connecteur();
       
        con = connect.connecttodb();
        String cin =cin_field.getText();
        String query = "SELECT * FROM banned WHERE cin = '"+cin+"'";
        String query1=" DELETE from banned where cin=?";
        try {
                
                Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);

                ResultSet res = stmt.executeQuery(query);
                if(res.next()){
                    res.first();
                    String mdp=res.getString("mot_de_pass");
                    cin = res.getString("CIN");
                    String nom = res.getString("nom");
                    String prenom = res.getString("prenom");
                    String tel = res.getString("tel");
                    String addres=res.getString("addresse");
                    String username=res.getString("username");
                    String email=res.getString("email");
                    Date date=res.getDate("date_de_naissance");
                    java.sql.Date sqlDate1 = new java.sql.Date(date.getTime());
                    String query2 = "INSERT INTO client VALUES (?,?,?,?,?,?,?,?,?)";

                                    try (PreparedStatement stmt1 = con.prepareStatement(query2)) {
                                        stmt1.setString(1, cin);
                                        stmt1.setString(2, nom);
                                        stmt1.setString(3, prenom);
                                        stmt1.setString(4, username);
                                        stmt1.setDate(5, sqlDate1); // Assuming sqlDate1 is your java.sql.Date object
                                        stmt1.setString(6, email);
                                        stmt1.setString(7, tel);
                                        stmt1.setString(8, addres);
                                        stmt1.setString(9, mdp);
                                        

                                        stmt1.executeUpdate();
                                        System.out.println("Data inserted successfully into client table.");                

                                    } catch (SQLException e) {
                                        System.out.println("Error inserting data into client table: " + e.getMessage());
                                    }
                                    
                    
                }
               try (
            // Establishing connection
            // Creating PreparedStatement
            PreparedStatement preparedStatement = con.prepareStatement(query1)
        ) {
            preparedStatement.setString(1, cin);
            preparedStatement.executeUpdate();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
            } catch (SQLException ex) {
                Logger.getLogger(listban.class.getName()).log(Level.SEVERE, null, ex);
            }
        load();
    }//GEN-LAST:event_unbanActionPerformed

    private void prenom_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenom_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenom_fieldActionPerformed

    private void refresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1ActionPerformed
        load();
    }//GEN-LAST:event_refresh1ActionPerformed
         

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cin_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField prenom_field;
    private javax.swing.JButton recherche;
    private javax.swing.JButton refresh1;
    private javax.swing.JTable table;
    private javax.swing.JButton unban;
    // End of variables declaration//GEN-END:variables
}
