/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ClientCRUD;

import Classes.Client;
import best_cars.MainPage;
import java.awt.Window;
import java.sql.Connection;
import java.sql.*;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author DELL
 */
public class AnnulerReservation extends javax.swing.JInternalFrame {
    private javax.swing.JDesktopPane jDesktopPane1;
    private Connection con;
    private Client client;

    /**
     * Creates new form AnnulerReservation
     */
    public AnnulerReservation() {
        initComponents();
    }
    public AnnulerReservation(javax.swing.JDesktopPane jDesktopPane1,Connection c,Client cl) {
        this.jDesktopPane1=jDesktopPane1;
        this.con=c;
        this.client=cl;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        annuler = new javax.swing.JButton();
        id_location = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        annuler.setText("ANNULER RESERVATION");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        jLabel1.setText("Code de Rservation :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_location, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annuler))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_location, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        String id = id_location.getText();
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM location WHERE ID='"+id+"' AND CIN='"+client.getCin()+"'";
            ResultSet res = stmt.executeQuery(sql);
            if(res.next()){
                
                Date datedeb = res.getDate("date_debut");

                // Convert java.sql.Date to LocalDate
                LocalDate localDateDebut = datedeb.toLocalDate();

                // Get the current date
                LocalDate currentDate = LocalDate.now();

                // Now you can compare the two LocalDate objects
                if (currentDate.isBefore(localDateDebut)) {
                    sql = "DELETE FROM LOCATION WHERE ID = '"+id+"'";
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"VOTRE RESERVATION EST ANNULER ");
                    
                    // Close all internal frames
                        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
                        for (JInternalFrame frame : frames) {
                            frame.dispose(); // Close the internal frame
                        }
                    
                    
                } else  {
                    if(res.getString("num_carte_bancaire") != null){
                        JOptionPane.showMessageDialog(null, "VOUS AVER DEJA PAYER CETTE LOCATION ", "Error", JOptionPane.ERROR_MESSAGE);
                    }else{
                        //si le client veut annuler une location (une reservation ) le jour de la reservation ou meme apres il sera BANNED car il nous a perdu de l'agrent
                        JOptionPane.showMessageDialog(null, " Malheureusement , Vous avez enfreint nos règles et vous serez banni(e) !!! ", "Error", JOptionPane.ERROR_MESSAGE);
                
                        //inserer le client dans le table banned 
                        sql="INSERT INTO banned VALUE (?)";
                        PreparedStatement pstmt = con.prepareStatement(sql);
                        pstmt.setString(1, client.getCin());
                        pstmt.executeUpdate();
                        
                        //delete the location from the table location
                        sql = "DELETE FROM location WHERE ID='"+id+"'";
                        stmt.executeUpdate(sql);
                        
                        
                        //close all
             
                        // Close all internal frames
                        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
                        for (JInternalFrame frame : frames) {
                            frame.dispose(); // Close the internal frame
                        }
                        // Get the parent frame and dispose of it
                        Window parentWindow = SwingUtilities.windowForComponent(jDesktopPane1);
                        parentWindow.dispose();
                        MainPage log =new MainPage();//thel wahda jdida
                        log.setLocationRelativeTo(null);
                        log.setVisible(true);//tkhaliha todhher
                        
                    }
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "VOUZ N'AVEZ PAS DE RESERVATION AYONS CE CODE = "+id, "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(AnnulerReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_annulerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JTextField id_location;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
