/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ClientCRUD;

import Classes.Client;
import best_cars.Login;
import best_cars.MainPage;
import java.awt.Window;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author DELL
 */
public class PayerPenalite extends javax.swing.JInternalFrame {
    private javax.swing.JDesktopPane jDesktopPane1;
    private Connection con;
    private Client client;
    private long days_en_retard;
    private double montant_penalite;
    private String id_location;
    
    /**
     * Creates new form PayerPenalite
     */
    public PayerPenalite() {
        initComponents();
    }
    public PayerPenalite(javax.swing.JDesktopPane jDesktopPane1,Connection c,Client cl,long days,double montant_penalite,String id_location) {
        this.jDesktopPane1=jDesktopPane1;
        this.con=c;
        this.client=cl;
        this.days_en_retard=days;
        this.montant_penalite=montant_penalite;
        this.id_location=id_location;
        initComponents();
        
        nb_jour_en_retard_field.setText(String.valueOf(days));
        penalite_field.setText(String.valueOf(montant_penalite));
        id_location_field.setText(id_location);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nb_jour_en_retard_field = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        num_carte_bancaire_field = new javax.swing.JTextField();
        payerbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        penalite_field = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_location_field = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel1.setText("nb jour en retard :");

        nb_jour_en_retard_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel2.setText("num carte bancaire :");

        num_carte_bancaire_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        payerbtn.setBackground(new java.awt.Color(255, 255, 102));
        payerbtn.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        payerbtn.setText("PAYER");
        payerbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        payerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payerbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel3.setText("montant de penalite :");

        penalite_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel4.setText("ID location :");

        id_location_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\Best_cars\\images\\pay (2).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nb_jour_en_retard_field, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(penalite_field, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(id_location_field, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(num_carte_bancaire_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_location_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nb_jour_en_retard_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(penalite_field, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_carte_bancaire_field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payerbtnActionPerformed
    if(num_carte_bancaire_field.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, " veillez inserer votre carte bancaire !!! ", "Error", JOptionPane.ERROR_MESSAGE);
    }else{
        String carte=num_carte_bancaire_field.getText();
        String sql="INSERT INTO penalite VALUE(?,?,?)";
        try {
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1, this.id_location);
            pstmt.setDouble(2, montant_penalite);
            pstmt.setString(3, carte);
            
            pstmt.executeUpdate();
            
            if(days_en_retard>=5){
                JOptionPane.showMessageDialog(null, " Malheureusement , Vous avez enfreint nos règles et vous serez banni(e) !!! ", "Error", JOptionPane.ERROR_MESSAGE);
                
                //inserer le client dans le table banned 
                sql="INSERT INTO banned VALUE (?)";
                pstmt.clearParameters();
                pstmt=con.prepareStatement(sql);
                pstmt.setString(1, this.client.getCin());
                
                pstmt.executeUpdate();
                
                
                //close all
             
                // Close all internal frames
                JInternalFrame[] frames = jDesktopPane1.getAllFrames();
                for (JInternalFrame frame : frames) {
                    frame.dispose(); // Close the internal frame
                }

                // Get the parent frame and dispose of it
                Window parentWindow = SwingUtilities.windowForComponent(jDesktopPane1);
                parentWindow.dispose();
                MainPage log =new MainPage();//thel wahda jdida
                log.setLocationRelativeTo(null);
                log.setVisible(true);//tkhaliha todhher
                
            }else{
                // Close all internal frames
                JInternalFrame[] frames = jDesktopPane1.getAllFrames();
                for (JInternalFrame frame : frames) {
                    frame.dispose(); // Close the internal frame
                }
                
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(PayerPenalite.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
        
        
    }//GEN-LAST:event_payerbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id_location_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nb_jour_en_retard_field;
    private javax.swing.JTextField num_carte_bancaire_field;
    private javax.swing.JButton payerbtn;
    private javax.swing.JLabel penalite_field;
    // End of variables declaration//GEN-END:variables
}
